name: Gatsby Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: ["opened", "synchronize"]

jobs:
  avoid-redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        if: ${{ github.event-name == 'push' }}
        run: npm run build
